[RSDungeonsConfig]
addDungeonsToModdedBiomes = true
blacklistedDungeonBiomes = ""

[RSDungeonsConfig.spawnrate]
badlandsDungeonSpawnrate = 8
darkForestDungeonSpawnrate = 8
desertDungeonSpawnrate = 8
jungleDungeonSpawnrate = 8
mushroomDungeonSpawnrate = 8
snowDungeonSpawnrate = 8
swampDungeonSpawnrate = 8
endDungeonSpawnrate = 8
netherDungeonSpawnrate = 8
oceanDungeonSpawnrate = 6

[RSDungeonsConfig.minHeight]
badlandsDungeonMinHeight = 2
darkForestDungeonMinHeight = 2
desertDungeonMinHeight = 2
jungleDungeonMinHeight = 2
mushroomDungeonMinHeight = 2
snowDungeonMinHeight = 2
swampDungeonMinHeight = 2
endDungeonMinHeight = 2
netherDungeonMinHeight = 2
oceanDungeonMinHeight = 3

[RSDungeonsConfig.maxHeight]
badlandsDungeonMaxHeight = 255
darkForestDungeonMaxHeight = 255
desertDungeonMaxHeight = 255
jungleDungeonMaxHeight = 255
mushroomDungeonMaxHeight = 255
snowDungeonMaxHeight = 255
swampDungeonMaxHeight = 255
endDungeonMaxHeight = 255
netherDungeonMaxHeight = 255
oceanDungeonMaxHeight = 255
[RSMainConfig]
blacklistedDimensions = "the_bumblezone:the_bumblezone"

[RSMainConfig.misc]
addSwampTreeToModdedBiomes = true
addBoulderToModdedBiomes = false
blacklistedSwampTreeBiomes = ""
blacklistedBoulderBiomes = ""
hornedSwampTree = true
boulderTiny = true
boulderGiant = true
diamondChanceInGiantBoulders = 7000
giantBouldersPerChunk = 1.0

[RSMainConfig.jungleFortress]
jungleFortressSpawnrate = 32
addJungleFortressToModdedBiomes = true
blacklistedFortressBiomes = ""
silverfishSpawnrateJF = 0.5
lootChestsJF = true

[RSMainConfig.igloos]
blacklistedIglooBiomes = ""
grassyIglooSpawnrate = 20
addGrassyIglooToModdedBiomes = false
stoneIglooSpawnrate = 20
addStoneIglooToModdedBiomes = false
[RSTemplesConfig.temples]
blacklistedTempleBiomes = ""
netherWastelandTempleSpawnrate = 27
addNetherWastelandTempleToModdedBiomes = false
netherBasaltTempleSpawnrate = 27
addNetherBasaltTempleToModdedBiomes = false
netherCrimsonTempleSpawnrate = 27
addNetherCrimsonTempleToModdedBiomes = false
netherWarpedTempleSpawnrate = 27
addNetherWarpedTempleToModdedBiomes = false
netherSoulTempleSpawnrate = 27
addNetherSoulTempleToModdedBiomes = false
[RSTemplesConfig.pyramids]
blacklistedPyramidBiomes = ""
netherPyramidSpawnrate = 37
addNetherPyramidToModdedBiomes = true
badlandsPyramidSpawnrate = 20
addBadlandsPyramidToModdedBiomes = true
[RSMineshaftsConfig]
lootChestsMS = true
addMineshaftsToModdedBiomes = true
blacklistedMineshaftBiomes = ""

[RSMineshaftsConfig.spawnrate]
birchMineshaftSpawnrate = 40
jungleMineshaftSpawnrate = 40
desertMineshaftSpawnrate = 40
stoneMineshaftSpawnrate = 40
savannaMineshaftSpawnrate = 40
icyMineshaftSpawnrate = 40
oceanMineshaftSpawnrate = 40
taigaMineshaftSpawnrate = 40
swampAndDarkForestMineshaftSpawnrate = 40
endMineshaftSpawnrate = 40
netherMineshaftSpawnrate = 40

[RSMineshaftsConfig.minHeight]
birchMineshaftMinHeight = 8
jungleMineshaftMinHeight = 8
desertMineshaftMinHeight = 8
stoneMineshaftMinHeight = 8
savannaMineshaftMinHeight = 8
icyMineshaftMinHeight = 8
oceanMineshaftMinHeight = 8
taigaMineshaftMinHeight = 8
swampAndDarkForestMineshaftMinHeight = 8
endMineshaftMinHeight = 30
netherMineshaftMinHeight = 8

[RSMineshaftsConfig.maxHeight]
birchMineshaftMaxHeight = 45
jungleMineshaftMaxHeight = 45
desertMineshaftMaxHeight = 45
stoneMineshaftMaxHeight = 45
savannaMineshaftMaxHeight = 45
icyMineshaftMaxHeight = 45
oceanMineshaftMaxHeight = 25
taigaMineshaftMaxHeight = 45
swampAndDarkForestMineshaftMaxHeight = 45
endMineshaftMaxHeight = 37
netherMineshaftMaxHeight = 13

[RSMineshaftsConfig.misc]
barrensIslandsEndMineshafts = false
[RSStrongholdsConfig]
strongholdSizeSH = 100.0
allowExtraSpawnersSH = true
lootChestsSH = true
blacklistedStrongholdBiomes = ""

[RSStrongholdsConfig.stonebrick]
allowStonebrickStronghold = true
addStonebrickStrongholdToModdedBiomes = true
silverfishSpawnrateSH = 0.8
stonebrickStrongholdMinHeight = 0
stonebrickStrongholdMaxHeight = 45
stonebrickStrongholdSpawnrate = 85
stonebrickStrongholdChainSpawnrate = 35

[RSStrongholdsConfig.nether]
netherStrongholdSpawnrate = 85
addNetherStrongholdToModdedBiomes = true
netherStrongholdMinHeight = 33
netherStrongholdMaxHeight = 36
netherStrongholdChainSpawnrate = 50
[RSOutpostsConfig]
blacklistedOutpostBiomes = ""

[RSOutpostsConfig.outposts]
netherBrickOutpostSpawnrate = 34
addNetherBrickOutpostToModdedBiomes = true
warpedOutpostSpawnrate = 34
addWarpedOutpostToModdedBiomes = true
crimsonOutpostSpawnrate = 34
addCrimsonOutpostToModdedBiomes = true
[RSVillagesConfig]
addVillagesToModdedBiomes = true
blacklistedVillageBiomes = ""
badlandsVillageSpawnrate = 17
birchVillageSpawnrate = 28
darkForestVillageSpawnrate = 28
jungleVillageSpawnrate = 26
swampVillageSpawnrate = 28
mountainsVillageSpawnrate = 28
giantTaigaVillageSpawnrate = 26
crimsonVillageSpawnrate = 30
warpedVillageSpawnrate = 30
[RSWellsConfig]
addWellsToModdedBiomes = true
blacklistedWellBiomes = ""
canHaveBells = true

[RSWellsConfig.spawnrate]
badlandsWellSpawnrate = 350
netherWellSpawnrate = 350
snowWellSpawnrate = 350
mossyStoneWellSpawnrate = 350
forestWellSpawnrate = 350
[RSShipwrecksConfig.blacklist]
blacklistedShipwreckBiomes = ""
addEndShipwreckToModdedBiomes = true
addNetherBricksShipwreckToModdedBiomes = true
addCrimsonShipwreckToModdedBiomes = true
addWarpedShipwreckToModdedBiomes = true
[RSShipwrecksConfig.spawnrate]
endShipwreckSpawnrate = 15
netherBricksShipwreckSpawnrate = 51
crimsonShipwreckSpawnrate = 41
warpedShipwreckSpawnrate = 41
